POST http://localhost:8080/api/books
Content-Type: application/json

{
    "title": "It",
    "isbn": "978-0012390123",
    "author": "Stephen King",
    "genre": "Horror",
    "available": true
}

###

DELETE http://localhost:8080/api/books/2

###

GET http://localhost:8080/api/books

###

POST https://symmetrical-meme-p6xv54gjgrx2w7x-8080.app.github.dev/checkout
Content-Type: application/json

{
    "firstName": "Rasheed",
    "lastName": "Abbasov",
    "address": "25 S Monmouth St, Dayton OH 45403",
    "date": "2026-06-15",
    "book": {
        "id": 3
    }
}

###

GET https://symmetrical-meme-p6xv54gjgrx2w7x-8080.app.github.dev/checkout/1
//Finds bookCheckout entity with id {id}

###

GET https://symmetrical-meme-p6xv54gjgrx2w7x-8080.app.github.dev/checkout
//Finds all bookCheckout entities

###

GET https://symmetrical-meme-p6xv54gjgrx2w7x-8080.app.github.dev/checkout/book/3
//Finds bookCheckout entity with bookid {bookId} attached to bookCheckout entity 

###

DELETE https://symmetrical-meme-p6xv54gjgrx2w7x-8080.app.github.dev/checkout/1
//Deletes bookCheckout entity with id {id}